### ISSUE TITLE
Unable to remove the CN top banner

### ISSUE THREAD

**Issue by yipu3** [harttle/no-leetcode-cn-redirect#1]
<img width="1202" alt="Screen Shot 2024-02-17 at 10 54 40" src="https://github.com/harttle/no-leetcode-cn-redirect/assets/5365604/ec83dcae-430a-47c7-8b10-ebf66bf7b416">

**Comment by harttle** [comment]
We have removed that on Leetcode homepage. Not sure with problems page, I'll take a look.

**Comment by yipu3** [comment]
> We have removed that on Leetcode homepage. Not sure with problems page, I'll take a look.

Neither the homepage.

<img width="1335" alt="Screen Shot 2024-02-17 at 13 09 24" src="https://github.com/harttle/no-leetcode-cn-redirect/assets/5365604/5ff2dcc4-f368-4b3a-a64d-446192a817bf">

Under development mode, it print out an error:

<img width="685" alt="Screen Shot 2024-02-17 at 13 09 34" src="https://github.com/harttle/no-leetcode-cn-redirect/assets/5365604/70ede30e-699c-454f-ac43-e5ae50a9b64d">

I rewrited `removeBanner` with the following code and it worked:

```js
function removeBanner() {
  log('removing banner');
  const leetCodeCnBannerCloseButton = document.getElementsByClassName(' duration-600 mt-2.5 h-6 w-6 shrink-0 cursor-pointer rounded-[50px] bg-[rgba(0,0,0,0.2)] text-center font-bold leading-5 text-white hover:bg-[rgba(0,0,0,0.7)] dark:bg-[rgba(255,255,255,0.18)]')[0];
  if (!leetCodeCnBannerCloseButton) {
    return;
  }
  leetCodeCnBannerCloseButton.click();
}
```

I am not a sophisticated frontend developer so I don't know if there is a more general way. Hope this snippet will help you.

**Comment by harttle** [comment]
Thank you for the details, it's very helpful. The challenge is the class list seems to be layout/style related, which can change overtime. I'm trying to find something identifiable and not likely subject to change.

**Comment by harttle** [comment]
Submited version 1.2 for review, should be available in a couple of days. Let's try the new version.
